---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
data:
  config.yaml: |
    storage:
      type: postgres
      path: "postgres://gatus:${POSTGRES_PASSWORD}@gatus-postgresql-rw.gatus-system.svc.cluster.local:5432/gatus?sslmode=disable"
    alerting:
      ntfy:
        url: http://192.168.18.211
        topic: homelab
        default-alert:
          failure-threshold: 3
          success-threshold: 3
          send-on-resolved: true