---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: twin
  namespace: flux-system
spec:
  interval: 120m
  url: https://twin.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gatus
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 60m
  targetNamespace: gatus-system
  values:
    service:
      type: LoadBalancer
      annotations:
        metallb.io/loadBalancerIPs: 192.168.18.209
    persistence:
      enabled: true
      size: 500Mi
    config:
      endpoints:
        - name: cloudnative-pg
          group: infrastructure
          url: http://cloudnative-pg-metrics.cloudnative-pg-system.svc.cluster.local:8080/metrics
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: cloudflared
          group: infrastructure
          url: http://cloudflared.cloudflared.svc.cluster.local:60123/metrics
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        # - name: eraser
        #   group: infrastructure
        #   url: http://cloudflared.eraser-system.svc.cluster.local/healthz
        #   interval: 30s
        #   conditions:
        #     - "[STATUS] == 200"
        #   alerts:
        #     - type: ntfy
        - name: openabo
          group: infrastructure
          url: http://openbao-system-openbao.openbao-system.svc.cluster.local:8200/v1/sys/health
          interval: 30s
          conditions:
            - "[STATUS] == any(200, 429, 472, 473, 501, 503)"
          alerts:
            - type: ntfy
        - name: external-secrets
          group: infrastructure
          url: http://external-secrets-system-external-secrets-metrics.external-secrets-system.svc.cluster.local:8080/metrics
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: metallb-controller
          group: infrastructure
          url: https://metallb-controller.metallb-system.svc.cluster.local:9443
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          client:
            insecure: true
          alerts:
            - type: ntfy
        - name: keycloak
          group: infrastructure
          url: "tcp://keycloak.keycloak-system-keycloak.svc.cluster.local"
          interval: 30s
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: ntfy
        - name: headlamp
          group: applications
          url: http://headlamp.headlamp-system.svc.cluster.local/
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: home-assistant
          group: applications
          url: http://homeassistant.homeassistant.svc.cluster.local/
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: mympd
          group: applications
          url: http://mympd.sound-system.svc.cluster.local/
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: mpd
          group: applications
          url: tcp://mpd.sound-system.svc.cluster.local:6600
          interval: 30s
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: ntfy
        - name: snapserver
          group: applications
          url: http://snapserver.sound-system.svc.cluster.local:1780/
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
      alerting:
        ntfy:
          url: http://192.168.18.211
          topic: homelab
          default-alert:
            failure-threshold: 3
            success-threshold: 2
            send-on-resolved: true
