---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: twin
  namespace: flux-system
spec:
  interval: 120m
  url: https://twin.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gatus
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 60m
  targetNamespace: gatus-system
  values:
    service:
      type: LoadBalancer
      annotations:
        metallb.io/loadBalancerIPs: 192.168.18.209
    persistence:
      enabled: true
      size: 500Mi
    config:
      endpoints:
        - name: CloudNativePG
          group: infrastructure
          url: http://cloudnative-pg-metrics.cloudnative-pg-system.svc.cluster.local:8080/metrics
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: Cloudflared
          group: infrastructure
          url: http://cloudflared.cloudflared.svc.cluster.local:60123/metrics
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: OpenBao
          group: infrastructure
          url: http://openbao-system-openbao.openbao-system.svc.cluster.local:8200/v1/sys/health
          interval: 30s
          conditions:
            - "[STATUS] == any(200, 429, 472, 473, 501, 503)"
          alerts:
            - type: ntfy
        - name: External Secrets
          group: infrastructure
          url: http://external-secrets-metrics.external-secrets-system.svc.cluster.local:8080/metrics
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: MetalLB Controller
          group: infrastructure
          url: https://metallb-controller-metrics.metallb-system.svc.cluster.local:9120/metrics
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          client:
            insecure: true
          alerts:
            - type: ntfy
        - name: MetalLB Speaker
          group: infrastructure
          url: https://metallb-speaker-metrics.metallb-system.svc.cluster.local:9120/metrics
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          client:
            insecure: true
          alerts:
            - type: ntfy
        - name: Keycloak
          group: infrastructure
          url: "tcp://keycloak.keycloak-system-keycloak.svc.cluster.local"
          interval: 30s
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: ntfy
        - name: Headlamp
          group: applications
          url: http://headlamp.headlamp-system.svc.cluster.local/
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: Home Assistant
          group: applications
          url: http://homeassistant.homeassistant.svc.cluster.local/
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: myMPD
          group: applications
          url: http://mympd.sound-system.svc.cluster.local/
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
        - name: MPD
          group: applications
          url: tcp://mpd.sound-system.svc.cluster.local:6600
          interval: 30s
          conditions:
            - "[CONNECTED] == true"
          alerts:
            - type: ntfy
        - name: Snapserver
          group: applications
          url: http://snapserver.sound-system.svc.cluster.local:1780/
          interval: 30s
          conditions:
            - "[STATUS] == 200"
          alerts:
            - type: ntfy
      alerting:
        ntfy:
          url: http://ntfy.ntfy-system.svc.cluster.local
          topic: status_ciansheehy_co
          default-alert:
            failure-threshold: 3
            success-threshold: 2
            send-on-resolved: true
