apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-tls-cert
  namespace: adguard
spec:
  secretName: adguard-tls-secret
  dnsNames:
    - dns.ciansheehy.co
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
