# https://github.com/helmforgedev/charts/blob/main/charts/adguard-home/values.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: helmforge
  namespace: flux-system
spec:
  interval: 120m
  url: oci://ghcr.io/helmforgedev/helm/adguard-home
  ref:
    tag: 1.5.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: helmforge
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 60m
  targetNamespace: adguard
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: adguard-adguard-adguard-home
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: adguard-adguard-adguard-home
                annotations:
                  reloader.stakater.com/auto: "true"
              spec:
                template:
                  spec:
                    hostNetwork: true
                    nodeSelector:
                      kubernetes.io/hostname: desktop-9th3sl8
                    dnsPolicy: ClusterFirstWithHostNet
  values:
    config:
      adGuardHome:
        http:
          address: 0.0.0.0:80
          session_ttl: 720h
          doh:
            insecure_enabled: true
        users:
          - name: admin
            password: "$2y$10$SuSeOQ9oUg/75q3u9/CRwO05zjyso96Oz7hLIDJXqkSpiyRkJPAEG"
        dns:
          bind_hosts:
            - 0.0.0.0
          port: 53
          upstream_dns:
            - https://dns.quad9.net/dns-query
            - https://dns.cloudflare.com/dns-query
          bootstrap_dns:
            - 9.9.9.9
            - 1.1.1.1
            - 8.8.8.8
          protection_enabled: true
          filtering_enabled: true
          cache_size: 4194304
        filters:
          - enabled: true
            url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
            name: AdGuard DNS filter
            id: 1
          - enabled: true
            url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
            name: AdAway Default Blocklist
            id: 2
        querylog:
          enabled: true
          interval: 720h
        statistics:
          enabled: true
          interval: 168h
        schema_version: 29
        tls:
          enabled: true
          server_name: dns.ciansheehy.co
          port_https: 0
          port_dns_over_tls: 853
          port_dns_over_quic: 0
          port_dnscrypt: 0
          certificate_path: /etc/adguardhome/certs/tls.crt
          private_key_path: /etc/adguardhome/certs/tls.key
    service:
      dns:
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.18.241
        extraPorts:
          - name: dns-tls
            port: 853
            targetPort: 853
            protocol: TCP
      web:
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.18.214
    extraVolumes:
      - name: adguard-tls
        secret:
          secretName: adguard-tls-secret
    extraVolumeMounts:
      - name: adguard-tls
        mountPath: /etc/adguardhome/certs
        readOnly: true
    persistence:
      conf:
        enabled: true
        size: 256Mi
        accessModes:
          - ReadWriteMany
        storageClass: nfs-storage
      work:
        enabled: true
        size: 5Gi
        accessModes:
          - ReadWriteMany
        storageClass: nfs-storage
