---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falcosidekick
  namespace: flux-system
spec:
  chart:
    spec:
      chart: falcosidekick
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  interval: 60m
  targetNamespace: falco
  values:
    webui:
      enabled: true
      replicaCount: 1