---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.202
  labels:
    app: homeassistant
  name: homeassistant
spec:
  ports:
    - name: homeassistant
      port: 80
      targetPort: 8123
  selector:
    app: homeassistant
  type: LoadBalancer