---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.221
spec:
  type: LoadBalancer
  ports:
    - port: 8096
      targetPort: 8096
  selector:
    app: jellyfin