---
apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: renovate
  namespace: renovate
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 2 * * *"
  timeZone: Europe/Dublin
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:44.65.2
              imagePullPolicy: Always
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: /etc/renovate/renovate.json
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-token
                      key: token
              volumeMounts:
                - name: renovate-config
                  mountPath: /etc/renovate
          volumes:
            - name: renovate-config
              configMap:
                name: renovate-config
