---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: renovate
spec:
  provider:
    vault:
      server: http://openbao-system-openbao.openbao-system.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-renovate
          serviceAccountRef:
            name: renovate
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-token
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: renovate-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: renovate-token
        property: token