---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets.yaml
  - cronjob.yaml
namespace: renovate
configMapGenerator:
  - name: renovate-config
    files:
      - renovate.json=config.json