- name: Setup k3s on server
  hosts: k3s_server
  become: true
  gather_facts: yes
  tasks:
    - name: Download and install K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        state: present
        timeout: 60

    - name: Ensure K3s ServiceLB is disabled in config.yaml
      ansible.builtin.blockinfile:
        path: /etc/rancher/k3s/config.yaml
        create: yes  # Creates the file if it does not exist
        mode: '0644'
        block: |
          disable:
            - servicelb
          kube-proxy-arg:
            - ipvs-strict-arp=true
          kube-apiserver-arg:
            - oidc-issuer-url=https://keycloak.ciansheehy.co/realms/master
            - oidc-client-id=headlamp
            - oidc-username-claim=preferred_username
            - oidc-groups-claim=groups

    - name: Verify the K3s service is active
      command: systemctl is-active --quiet k3s
      changed_when: false

    - name: Set permissions for K3s kubeconfig
      command: chmod 644 /etc/rancher/k3s/k3s.yaml

    - name: Get node join token
      become: true
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/token
        dest: 'node_join_token'
        flat: yes

    - name: Restart k3s service to ensure it picks up the new configuration
      command: systemctl restart k3s