apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  labels:
    app: wizarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizarr
  template:
    metadata:
      labels:
        app: wizarr
    spec:
      containers:
        - name: wizarr
          image: ghcr.io/wizarrrr/wizarr:v2026.9.1
          ports:
            - containerPort: 5690
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: DISABLE_BUILTIN_AUTH
              value: "false"
            - name: TZ
              value: Etc/UTC
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wizarr-data