---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mpd
  name: mpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpd
  template:
    metadata:
      labels:
        app: mpd
    spec:
      containers:
        - image: ghcr.io/cmacsithigh/mpd:1.1.1
          imagePullPolicy: Always
          name: mpd
          ports:
            - containerPort: 6600
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /fifo
              name: fifo
            - mountPath: /var/lib/mpd/playlists
              name: playlists
              subPath: playlists
      initContainers:
        - name: init-fifo
          image: ghcr.io/cmacsithigh/mpd:1.1.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              mkdir -p /fifo || true
              if [ ! -p /fifo/mpd.fifo ]; then mkfifo /fifo/mpd.fifo || true; fi
              chown 1000:1000 /fifo || true
              chown 1000:1000 /fifo/mpd.fifo || true
          securityContext:
            runAsUser: 0
      hostname: mpd
      volumes:
        - persistentVolumeClaim:
            claimName: mpd-fifo
          name: fifo
        - persistentVolumeClaim:
            claimName: mympd
          name: playlists