---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: music-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
    spec:
      hostNetwork: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: server
          image: ghcr.io/music-assistant/server:2.10.3
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /data
          # Internal health check for the web dashboard engine
          livenessProbe:
            httpGet:
              path: /
              port: 8095
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: music-assistant-pvc