apiVersion: v1
kind: ConfigMap
metadata:
  name: music-assistant-radios
spec:
  bbc_radio_6.m3u: |
    #EXTM3U
    #EXTINF:1,BBC Radio 6 Music
    #EXTGENRE:Indie
    #PLAYLIST:BBC Radio 6 Music
    #EXTIMG:https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpQQyFb3eDlEmKfVpEHtqRb6Yx1Z91XxhR_g&s
    #HOMEPAGE:
    #COUNTRY:United Kingdom
    #STATE:
    #LANGUAGE:English
    #DESCRIPTION:
    #CODEC:MP3
    #BITRATE:192
    http://as-hls-ww-live.akamaized.net/pool_81827798/live/ww/bbc_6music/bbc_6music.isml/bbc_6music-audio%3d96000.norewind.m3u8
  fip.m3u: |
    no#EXTM3U
    #EXTINF:1,FIP
    #EXTGENRE:Indie
    #PLAYLIST:FIP
    #EXTIMG:https://upload.wikimedia.org/wikipedia/commons/1/16/FIP_logo_2021.svg
    #HOMEPAGE:
    #COUNTRY:France
    #STATE:
    #LANGUAGE:French
    #DESCRIPTION:
    #CODEC:MP3
    #BITRATE:192
    https://icecast.radiofrance.fr/fip-hifi.aac?id=radiofrance
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: music-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
    spec:
      hostNetwork: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: radio-file-sync
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /data/radios
              cp /config-radios/* /data/radios/
              echo "Radio playlist files successfully updated inside the PVC storage."
          volumeMounts:
            - name: data
              mountPath: /data
            - name: radio-config-volume
              mountPath: /config-radios
      containers:
        - name: server
          image: ghcr.io/music-assistant/server:2.10.3
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 8095
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: music-assistant-pvc
        # 2. Maps your text-based radio list directly into the deployment
        - name: radio-config-volume
          configMap:
            name: music-assistant-radios
