---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mympd
  name: mympd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mympd
  template:
    metadata:
      labels:
        app: mympd
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Dublin
            - name: UMASK_SET
              value: '022'
            - name: MPD_HOST
              value: mpd.sound-system.svc.cluster.local
            - name: MYMPD_SSL
              value: 'false'
            - name: MYMPD_HTTP_PORT
              value: '8080'
          image: ghcr.io/cmacsithigh/mympd:1.1.2
          imagePullPolicy: Always
          name: mympd
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/mympd
              name: mympd
              subPath: workdir
            - mountPath: /var/cache/mympd
              name: mympd
              subPath: cachedir
            - mountPath: /var/lib/mpd/playlists
              name: mympd
              subPath: playlists
            - mountPath: /mystate
              name: mympd
              subPath: state
            - mountPath: /var/lib/mympd/webradios
              name: mympd
              subPath: radios
            - mountPath: /var/lib/mympd/pics/thumbs
              name: mympd
              subPath: pictures
            - mountPath: /var/lib/mympd/scripts
              name: mympd
              subPath: lua_scripts
      hostname: mympd
      initContainers:
        - command:
            - sh
            - /scripts/copy-files.sh
          image: ghcr.io/cmacsithigh/mympd:1.1.2
          imagePullPolicy: Always
          name: init-copy-files
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /var/lib/mympd
              name: mympd
              subPath: workdir
            - mountPath: /var/cache/mympd
              name: mympd
              subPath: cachedir
            - mountPath: /var/lib/mpd/playlists
              name: mympd
              subPath: playlists
            - mountPath: /mystate
              name: mympd
              subPath: state
            - mountPath: /var/lib/mympd/webradios
              name: mympd
              subPath: radios
            - mountPath: /var/lib/mympd/pics/thumbs
              name: mympd
              subPath: pictures
            - mountPath: /var/lib/mympd/scripts
              name: mympd
              subPath: lua_scripts
      nodeSelector:
        kubernetes.io/hostname: server
      volumes:
        - name: mympd
          persistentVolumeClaim:
            claimName: mympd