---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: music-assistant
  name: music-assistant
spec:
  ports:
    - name: music-assistant
      port: 8095
      targetPort: 8095
  selector:
    app: music-assistant
  type: ClusterIP