---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: music-assistant
  name: music-assistant
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.204
spec:
  ports:
    - name: music-assistant
      port: 8095
      targetPort: 8095
  selector:
    app: music-assistant
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: music-assistant
  name: music-assistant-snapcast
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.205
spec:
  ports:
    - name: snapcast-stream
      port: 1704
      targetPort: 1704
      protocol: TCP
    - name: snapcast-control
      port: 1705
      targetPort: 1705
      protocol: TCP
  selector:
    app: music-assistant
  type: LoadBalancer