---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mpd
  name: mpd
spec:
  ports:
    - name: mpd
      port: 6600
      targetPort: 6600
  selector:
    app: mpd
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mympd
  name: mympd
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: mympd
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: snapserver
  name: snapserver
spec:
  ports:
    - name: http
      port: 1705
      targetPort: 1705
  selector:
    app: snapserver
  type: LoadBalancer