---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snapserver
  name: snapserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapserver
  template:
    metadata:
      labels:
        app: snapserver
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: ghcr.io/cmacsithigh/snapserver:1.1.4
          imagePullPolicy: Always
          name: snapserver
          ports:
            - containerPort: 1704
            - containerPort: 1705
            - containerPort: 1780
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /fifo
              name: fifo
      hostname: snapserver
      volumes:
        - name: fifo
          persistentVolumeClaim:
            claimName: mpd-fifo