---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snapserver
  name: snapserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapserver
  template:
    metadata:
      labels:
        app: snapserver
    spec:
      containers:
        - image: ghcr.io/cmacsithigh/snapserver:1.2.2
          imagePullPolicy: Always
          name: snapserver
          ports:
            - containerPort: 1704
            - containerPort: 1705
            - containerPort: 1780
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /fifo
              name: fifo
            - mountPath: /run/avahi-daemon/socket
              name: host-avahi-socket
              readOnly: true
            - mountPath: /var/run/dbus/system_bus_socket
              name: host-dbus-socket
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostname: snapserver
      nodeSelector:
        kubernetes.io/hostname: pi4-server
      volumes:
        - name: fifo
          persistentVolumeClaim:
            claimName: mpd-fifo
        - hostPath:
            path: /run/avahi-daemon/socket
            type: Socket
          name: host-avahi-socket
        - hostPath:
            path: /var/run/dbus/system_bus_socket
            type: Socket
          name: host-dbus-socket