---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-system
resources:
  - jellyfin.yaml
  - namespace.yaml
  - pvcs.yaml
  - qtorrent.yaml
  - radarr.yaml
  - services.yaml
  - sonarr.yaml