---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-system
resources:
  - jellyfin
  - maintainerr
  - prowlarr
  - qbittorrent
  - radarr
  - sabnzbd
  - seerr
  - sonarr
  - shared-pvc.yaml
  - namespace.yaml