apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-system
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - pi4-server
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.6.5
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: DOTNET_SYSTEM_NET_DISABLEIPV6
              value: "1"
          ports:
            - containerPort: 9696
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.5.2
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 8191
              name: flaresolverr
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
