---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-storage
