apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: descheduler
resources:
  - https://github.com/kubernetes-sigs/descheduler/kubernetes/cronjob?ref=release-1.34
  - namespace.yaml

patches:
  - patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: descheduler
      spec:
        schedule: "*/15 * * * *"
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: descheduler-policy-configmap
      data:
        policy.yaml: |
          apiVersion: "descheduler/v1alpha2"
          kind: "DeschedulerPolicy"
          profiles:
            - name: default
              pluginConfig:
              - name: "DefaultEvictor"
                args:
                  ignorePvcPods: true
                  nodeFit: true
              - name: "RemoveDuplicates"
              - name: "RemovePodsViolatingInterPodAntiAffinity"
              - name: "LowNodeUtilization"
                args:
                  thresholds:
                    "cpu": 30
                    "memory": 50
                    "pods": 30
                  targetThresholds:
                    "cpu": 50
                    "memory": 60
                    "pods": 50
              plugins:
                balance:
                  enabled:
                    - "RemoveDuplicates"
                    - "LowNodeUtilization"
                deschedule:
                  enabled:
                    - "RemovePodsViolatingInterPodAntiAffinity"