all:
  children:
    homelab:
      hosts:
        server:
          ansible_host: 192.168.18.10
        rc0:
          ansible_host: 192.168.18.13
        desktop:
          ansible_host: 192.168.18.14
        rc2:
          ansible_host: 192.168.18.11

    k3s:
      hosts:
        server:
        desktop:

    k3s_nodes:
      hosts:
        desktop:

    k3s_server:
      hosts:
        server:
