all:
  children:
    homelab:
      hosts:
        server:
          ansible_host: 192.168.18.10
        desktop:
          ansible_host: 192.168.18.14
        rc0:
          ansible_host: 192.168.18.13 # bedroom
        rc2:
          ansible_host: 192.168.18.11 # hallway
        rc3:
          ansible_host: 192.168.18.19 # office

    k3s:
      hosts:
        server:
        desktop:

    k3s_nodes:
      hosts:
        desktop:

    k3s_server:
      hosts:
        server:

    speakers:
      hosts:
        rc0:
        rc2:
        rc3:
