apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--renovate
spec:
  schedules:
    - "0 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: renovate
        - name: k8s-secret-name
          value: renovate-token
        - name: k8s-secret-key
          value: token
        - name: proton-item-name
          value: GITHUB_TOKEN
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--keycloak
spec:
  schedules:
    - "5 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: keycloak-system
        - name: k8s-secret-name
          value: keycloak-credentials
        - name: k8s-secret-key
          value: password
        - name: proton-item-name
          value: KEYCLOAK_TOKEN
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--cloudflared
spec:
  schedules:
    - "10 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: cloudflared
        - name: k8s-secret-name
          value: cloudflared-credentials
        - name: k8s-secret-key
          value: token
        - name: proton-item-name
          value: CLOUDFLARED_TUNNEL_TOKEN
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--cloudflare-dns
spec:
  schedules:
    - "15 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: cert-manager
        - name: k8s-secret-name
          value: cloudflare-dns-token
        - name: k8s-secret-key
          value: token
        - name: proton-item-name
          value: CLOUDFLARE_DNS_TOKEN
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--headlamp
spec:
  schedules:
    - "20 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: flux-system
        - name: k8s-secret-name
          value: headlamp-client
        - name: k8s-secret-key
          value: secret
        - name: proton-item-name
          value: HEADLAMP_CLIENT_SECRET
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--konflate-app-id
spec:
  schedules:
    - "25 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: flux-system
        - name: k8s-secret-name
          value: konflate-app-id
        - name: k8s-secret-key
          value: appClientId
        - name: proton-item-name
          value: KONFLATE_APP_CLIENT_ID
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--konflate-app-private-key
spec:
  schedules:
    - "25 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: flux-system
        - name: k8s-secret-name
          value: konflate-app-private-key
        - name: k8s-secret-key
          value: appPrivateKey
        - name: proton-item-name
          value: KONFLATE_APP_PRIVATE_KEY
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--konflate-webhook-secret
spec:
  schedules:
    - "25 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: flux-system
        - name: k8s-secret-name
          value: konflate-webhook-secret
        - name: k8s-secret-key
          value: webhookSecret
        - name: proton-item-name
          value: KONFLATE_WEBHOOK_SECRET
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--openvpn-user
spec:
  schedules:
    - "30 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: media-system
        - name: k8s-secret-name
          value: openvpn-user
        - name: k8s-secret-key
          value: OPENVPN_USER
        - name: proton-item-name
          value: OPENVPN_USER
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: protonpass--openvpn-password
spec:
  schedules:
    - "30 * * * *"
  timezone: "Europe/Dublin"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: protonpass-secret-syncer
    arguments:
      parameters:
        - name: target-namespace
          value: media-system
        - name: k8s-secret-name
          value: openvpn-password
        - name: k8s-secret-key
          value: OPENVPN_PASSWORD
        - name: proton-item-name
          value: OPENVPN_PASSWORD