---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
        - name: nzbget
          image: ghcr.io/nzbgetcom/nzbget:v26.3
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 6789
              name: webui
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media-storage
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config-pvc
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-storage-pvc # Shared storage PVC across Servarr apps
