---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.228
spec:
  ports:
    - port: 9091
      targetPort: 9091
      name: webui
  selector:
    app: transmission
