---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 120m
  url: oci://registry.suse.com/edge/charts/metallb
  ref:
    tag: 305.0.1+up0.15.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: metallb
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 60m
  targetNamespace: metallb-system