---
apiVersion: v1
kind: Service
metadata:
  name: maintainerr
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.225
spec:
  selector:
    app: maintainerr
  ports:
    - port: 6246
      targetPort: 6246