---
- name: Create Renovate Secret
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: vault_token
      prompt: "Enter the Vault token"
      private: true
    - name: secret_value
      prompt: "Enter the secret value for renovate"
      private: true
  roles:
    - role: create_openbao_secret
      vars:
        secret_name: renovate-token
        secret_key: token
        secret_value: "{{ secret_value }}"
        vault_addr: "{{ vault_addr }}"
        vault_token: "{{ vault_token }}"
