---
- name: Create Keycloak Secret
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: vault_token
      prompt: "Enter the Vault token"
      private: true
    - name: secret_value
      prompt: "Enter the secret value for keycloak"
      private: true
  roles:
    - role: create_openbao_secret
      vars:
        secret_name: keycloak-credentials
        secret_key: password
