---
- name: Setup Ansible User and Distribute SSH Keys
  hosts: localhost
  gather_facts: yes
  vars:
    ansible_key_path: "~/.ssh/ansible_key.pub"
  tasks:
    - name: Check if local SSH public key exists
      stat:
        path: "{{ ansible_key_path }}"
      register: ssh_key_stat

    - name: Fail if local SSH public key not found
      fail:
        msg: "SSH key not found at {{ ansible_key_path }}"
      when: not ssh_key_stat.stat.exists

    - name: Read local SSH public key content
      slurp:
        src: "{{ ansible_key_path }}"
      register: ssh_key_content

- name: Configure Target Hosts
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    new_ansible_user: "ansible"
    ssh_key_pub: "{{ hostvars['localhost']['ssh_key_content']['content'] | b64decode | trim }}"

  tasks:
    - name: Ensure the new ansible user exists
      user:
        name: "{{ new_ansible_user }}"
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Ensure the SSH public key is added to the ansible user
      authorized_key:
        user: "{{ new_ansible_user }}"
        state: present
        key: "{{ ssh_key_pub }}"

    - name: Ensure passwordless sudo for the ansible user
      lineinfile:
        path: "/etc/sudoers.d/{{ new_ansible_user }}"
        state: present
        create: yes
        mode: '0440'
        line: "{{ new_ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"