apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: caddy
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: base
    - name: media-system
  path: ./gitops/apps/caddy
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true