---
reporting:
  interval: 30s
web:
  enabled: true
  config:
    authentication:
      anonymous:
        groups:
          - flux-admin
        username: flux
      type: Anonymous
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    className: traefik
    enabled: true
    hosts:
      - host: ''
        paths:
          - path: /
            pathType: Prefix