[http]
enabled = true

[stream]
source = spotify:///librespot?name=Spotify&bitrate=320&volume=100&devicename=🔊 Kinsale Be Jamming
source = pipe:///fifo/mpd.radio?name=Radio

[audio]
output = audioresample ! audio/x-raw,rate=44100,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/fifo/snap.output