---
apiVersion: v1
kind: Service
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  ports:
    - name: webhook-server
      port: 9443
      targetPort: webhook-server
  selector:
    app: metallb
    component: controller
  type: ClusterIP