---
apiVersion: v1
kind: Service
metadata:
  name: metallb-controller-metrics
  namespace: metallb-system
spec:
  ports:
    - name: metrics
      port: 9120
      targetPort: metricshttps
  selector:
    app: metallb
    component: controller
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-speaker-metrics
  namespace: metallb-system
spec:
  ports:
    - name: metrics
      port: 9120
      targetPort: metricshttps
  selector:
    app: metallb
    component: speaker
  type: ClusterIP