---
apiVersion: v1
kind: Service
metadata:
  name: metallb-controller
  namespace: metallb-system
  annotations:
    gatus.home-operations.com/enabled: "false"
spec:
  ports:
    - name: healthz
      port: 17472
      targetPort: healthz
  selector:
    app: metallb
    component: controller
  type: ClusterIP