---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
  ## Replace this with your IP address reserved range.
  ## This should be on the same network as your nodes!
  ## This address range should be blocked on your router DHCP config
  - 192.168.18.210-192.168.18.230
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ip-pool-l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - ip-pool