apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    jellyfin.ciansheehy.co {
        tls /certs/tls.crt /certs/tls.key
        reverse_proxy jellyfin.media-system.svc.cluster.local:8096
    }