apiVersion: v1
kind: Service
metadata:
  name: caddy
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.227
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      name: http
    - port: 443
      targetPort: https
      name: https
  selector:
    app: caddy