---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: keycloak
  namespace: keycloak-system
spec:
  provider:
    vault:
      server: http://openbao-system-openbao.openbao-system.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-keycloak
          serviceAccountRef:
            name: keycloak-system-keycloak
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: keycloak-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: keycloak-credentials
        property: password