# General location of things #################################
playlist_directory      "/var/lib/mpd/playlists"

# General music daemon options ###############################
bind_to_address         "0.0.0.0"
port                    "6600"

# Decoder ####################################################
decoder {
        plugin          "hybrid_dsd"
        enabled         "no"
}

decoder {
        plugin          "wildmidi"
        enabled         "no"
}

# Audio Output ###############################################
audio_output {
	type "fifo"
	name "Kinsale Radio"
	path "/fifo/mpd.radio"
	format "48000:16:2"
	mixer_type "software"
}

input {
    plugin "curl"
}

input {
    plugin "qobuz"
    app_id "950096963"
    app_secret "8c775a2d04a6058e0a16ec1ff7038cf4"
    username "your_qobuz_email@example.com"
    password "your_qobuz_password"
    format_id "6"
}